### ISSUE TITLE
Support for data files in cldf format

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#1]
It would be nice, if BEASTling could handle [cldf](https://github.com/glottobank/cldf) data out-of-the-box, i.e. a matrix

```
iso    f1    f2    ...
abc    1     0    ...
cde    0     1    ...
```

would be encoded as

```
abc    f1    1
abc    f2    0
cde    f1    0
cde    f2    1
```

**Comment by lmaurits** [comment]
Hi Robert, sorry for the late action on this, I somehow completely missed the notification email.  I agree that this would be a nice and sensible thing to support, and it shouldn't be too much work.  I'll try to get this added soon.

**Comment by lmaurits** [comment]
Hi Robert.  I finally got around to doing some work on this.  Preliminary CLDF support is now in the repository, but I wanted to run through the implementation with you and ask for your input.

At the moment, BEASTling assumes that a provided .csv file is a CLDF file if its header contains the three fields "Language_ID", "Feature_ID" and "Value".  Additional fields are okay, they will be ignored.  If any one of these fields is missing then the file will be parsed as per the standard BEASTling matrix format.

This is a fairly strict interpretation of CLDF, which seems to me to be designed to give people quite a bit of freedom with regard to fields and filednames.  However, the names I am insisting on are the ones generated by the CLLD toolkit, so I think this should work out okay.

Would you suggest I do anything additional or differently?

Btw, even with this change, BEASTling will not yet work on CLDF data sets "out of the box", as most CLDF data already available use URLs for Language_IDs, and BEASTling insists upon ISO codes.  However, this restriction is next in line to be loosened, so hopefully soon existing CLDF datasets will "just work".

**Comment by lmaurits** [comment]
Oops, please read "Parameter_ID" for "Feature_ID" in the above.

**Comment by xrotwang** [comment]
This implementation is completely in line with the intention of CLDF - i.e. whenever tools provide logic for handling data in columns with particular names, this will create an ad-hoc standard, which - if taken up by others - will make it into the next version of CLDF. This sort of standardisation seems to have worked quite well for [flickr machine tags](https://www.flickr.com/groups/51035612836@N01/discuss/72157594497877875/), so I hope it will work here as well.

`Language_ID` and `Value` have already passed that stage, while `Parameter_ID` still has a bit of a fight against `Feature_ID` :)

**Comment by xrotwang** [comment]
Btw. I wanted to try out a complete processing pipeline from GramBank to BEASTling, but haven't gotten around to install a new JAVA runtime which seems to be required by BEAST. Could I run an older version of BEAST with Java 1.7? And would this be compatible with BEASTling?

**Comment by xrotwang** [comment]
Never mind, I finally got around to update Java on my end.

**Comment by lmaurits** [comment]
Do you think it would be better to change BEASTling so that it will accept either `Parameter_ID` or `Feature_ID`, or is it better to "take a stand" to help hurry along the ad-hoc standardisation?

BEASTling should be compatible with any version of BEAST 2.x.  If you'd tried the latest version of BEAST 2 which worked on Java 7, I suspect that everything would have gone smoothly.  However, the BEAST team are very quick to adopt new Java features, so sticking with an old version will probably break a lot of packages.

I'm very interested in the GramBank to BEASTling pipeline, please keep me up to date with your efforts!

**Comment by xrotwang** [comment]
I think `Feature_ID` will turn out the winner, and it's the one I've chosen for the [GramBank data](https://github.com/glottobank/Grambank/blob/master/datasets/africa/akan1250.tsv).

**Comment by lmaurits** [comment]
Well, there's no sense in reducing compatibility with Grambank!  I've switched it to Feature_ID.  It's a very quick and easy fix, anyway, if somebody wants to use an existing file with Parameter_ID in the header.

I'm closing this issue now, feel free to open a new one if you discover any other CLDF-related issues.
