### ISSUE TITLE
Tutorial: Comment is wrong

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#107]
As a minor point, one of our first examples says

    [... The same output as before, and the new directory:]

We have never `dir`ed the starting directory.

**Comment by lmaurits** [comment]
It seems to me that we have?

> Type `dir` and press Enter. The shell should show you the contents of the directory you are in, which is probably your home directory.

**Comment by Anaphory** [comment]
Ah, right! That makes sense, I was just looking at the two subsequent `dir` examples and thinking "THAT's not the same output!"
