### ISSUE TITLE
Covarion model input handling

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#12]
The documentation states:

> Note that in order to use the Covarion model, you should not provide your data in binary format (i.e. do not use a .csv file full of 1s and 0s).  Instead, provide your data in multistate format, i.e., in the case of cognate data one column per meaning slot, with values corresponding to cognate class membership.  BEASTling will automatically translate this into the appropriate number of binary features.  This approach means that you can have a single data file which can be used to generate binary and multistate analyses, and also lets BEASTling share mutation rates across binary features corresponding to a single meaning slot.

On the other hand, this does not allow me to use a covarion model where a meaning class can be represented by multiple cognate classes. It would therefore be nice to have the option to use either convention.

**Comment by lmaurits** [comment]
BEASTling now attempts to recognise whether a data file has already been binarised (by counting the number of distinct non-? values for each feature and seeing if it is always 2), and refrains from rebinarising if this is the case.  The behaviour can be explicitly controlled by setting "binarised" (or "binarized") to True/False in the [model] section.  The documentation has been updated.  Will this solve the problem with your use case?

**Comment by lmaurits** [comment]
Until presented with evidence to the contrary, I am going to assume that this works fine now.  Reopen if your pre-binarised file(s) ever break(s).
