### ISSUE TITLE
Reference all major elements in the XML as attributes of BeastXml

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#120]
When working at the cutting edge (i.e. using unpublished BEAST features not yet ready for public consumption and hence not supported directly by BEASTling), it's still useful to use BEASTling to do 90% of the work in configuring an analysis, and then using a small script to directly access the `ElementTree` inside a `BeastXml` object and tack in a few extra operators or whatever.

Appending something inside of the `<run>` block, for example, is quick and easy, because `BeastXml.run` is a pointer to the `<run>` element, so one can add to it directly without having to use ElementTree functionality to search for the relevant element.  But changing something inside the `<init>` block, say, is not so easy, because there is no `BeastXml.init` one can just grab, one has to search.

We should consistently provide easy access to the major parts of the tree to make hacking a config more pleasant.

**Comment by xrotwang** [comment]
I guess it wouldn't be particularly difficult to simply add a section `custom` or similar, where option names are [XPaths](https://docs.python.org/2/library/xml.etree.elementtree.html#xpath-support) and option values could be some sort of YAML specifying elements to be inserted.

**Comment by lmaurits** [comment]
This wasn't too hard, most things were actually already named.  The new attributes on BeastXml are `self.init` and `self.tree`, and `self.master_distribution` was renamed to the rather more sensible `self.posterior`.

**Comment by Anaphory** [comment]
This makes the objects available for python code, but not – as suggested by @xrotwang – immediately through the config file, right?

(No issue with that, I just wanted to have that stated explicitly.)

**Comment by lmaurits** [comment]
Yes, that is the current situation.  I kind of balked at the idea of having super gross-looking XPath/YAML code in BEASTling configs.  Perhaps I could be persuaded otherwise, if people really think this is necessary.  But I imagine such an approach would not be adequate for all feasible hacks, so why bother?
