### ISSUE TITLE
Duplicate Beast IDs (Comma in name and Rate Variation)

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#124]
Before you look at this in more detail, let me check whether this came about due to my configparser shenannigans – a very similar file did work a moment ago. But the fact that Beastling *can* output this, even though probably after being given a messy configuration object, is disturbing.

Beast complains about a `beastling`-generated XML:
```
IDs should be unique. Duplicate id 'featureClockRate:lexicon:flat' found

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <state id='state'>
              <parameter id='featureClockRate:lexicon:flat' name='stateNode'>
```

The ini file is

```
[admin]
basename = lessersunda_noproto_ratevariation_autocode

[languages]
exclusions = p-aust1307-abvd,p-aust1307-acd,p-cent2245-abvd,p-cent2245-acd,p-mala1545-abvd,p-mala1545-acd,hama1240,p-alor1249,p-timo1261,p-east2519

[model lexicon]
model = covarion
data = auto_data.tsv
file_format = cldf
rate_variation = True
```

**Comment by Anaphory** [comment]
Argh!

The error comes from the fact that my data file contains two features, “flat” and “flat, smooth”. For some reason, beast thinks it's a good idea to *split ids at commas and use the first part*, so beastling will have to make sure to never put commas in ids. (I'll check what spaces do.)

We do have tests for feature names involving commas, but apparently not with rate variation and the possibility of confusion.

**Comment by Anaphory** [comment]
I ran `beastling tests/configs/admin.conf tests/configs/mk.conf tests/configs/cldf_data_with_comma.conf tests/configs/rate_var.conf`, which gave me a `beastling_test.xml` that beast chokes on.

So I have now added `("admin", "mk", "cldf_data_with_comma", "rate_var"),` to the list of configs in `beastrun_tests.py`.

**Comment by Anaphory** [comment]
Dammit, this is hard. Doing this properly would require keeping track of all `id`s. This requires fiddling with every single call to one of the `ElementTree` factories.

I don't want a half-baked solution that introduces errors that are even less obvious, so I'll think about where to document this. Otherwise I will put this off for the moment, fix my data, and store this issue in the same File 13 as my previous suggestion for building a cleaner XML builder which knows beast's logic with `idref`s, `@`s, `name`s, tags, `spec`s and `id`s and could build nicer element networks for us.

**Comment by Anaphory** [comment]
Note: Due to https://github.com/CompEvol/beast2/issues/657, we should also not permit `'` and probably `"` inside the IDs we write to the xml.

**Comment by Anaphory** [comment]
There is currently a test for this, resulting in
```
AssertionError: Beast run on ('admin', 'mk', 'cldf_data_with_comma', 'rate_var') returned non-zero exit status 1
```


What is the clean test-driven development/nosetest/travis way to say “This test is a reminder of documented buggy behaviour, continue running it but don't consider its failure a deal-breaker for the software”?

@xrotwang – You know this stuff far better than I do, what do you suggest?

**Comment by Anaphory** [comment]
I mean, this is not urgent due to the travis magic in our tests, which means that this is reported as a *successful* test, but it's just not a clean thing in our test suite.

**Comment by xrotwang** [comment]
Maybe run this one test in a `with TestCase.assertRaises(AssertionError)` block? And document why the error is expected right there?

**Comment by Anaphory** [comment]
Maybe it's best to mark that test explicitly as `skipped`. That way (a) we don't have a problem with the fact that it will continue to not raise `AssertionError` on travis, and (b) every test run will quasi say “This test was skipped! (Check the code to see why.)”

Apparently NoseTest has a `SkipTest` exception which is handled to do that.

**Comment by Anaphory** [comment]
Hm, somehow I expected `nosetest` to report an `S` for this among the
```
..........EEEEF......
```
