### ISSUE TITLE
`language_column` is not removed as expected

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#13]
I thought I had already adapted the code to remove the `language_column` from the data even when it is not called `iso`, but the issue is still there.

**Comment by lmaurits** [comment]
I have changed the code which previously only removed "iso" from the data, and also added a test case for the "language_column" option (see tests/configs/nonstandard_lang_col.conf and tests/data/nonstandard_lang_col.csv).  It seems to me that this is all working properly now.  Can you please confirm that this is working for whatever data you were using when you opened this Issue?

**Comment by lmaurits** [comment]
I'm assuming this is now fixed because the nonstandard_lang_col tests are passing fine, so I'm closing the issue.  Please re-open if you find further problems.
