### ISSUE TITLE
Documentation does not talk about `-p` option

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#131]
The documentation must mention the `--prior` option and say what it does to `basename` (and not only in the tutorial where I put it now).

**Comment by Anaphory** [comment]
The tutorial does now, it's still missing from the core. We should probably have a doc page on the cli, which expands on the ArgumentParser help message.

**Comment by lmaurits** [comment]
I guess the "usage" page has more or less ended up as a CLI page?  It already mentions `--overwrite`, `--verbose`, `--extract` and `--report`.  I'll add this there for now, I guess.

Would probably be good to also mention `--help`!  The output from that is the one place where `--prior` is actually documented.

**Comment by lmaurits** [comment]
All currently existing command line options are now mentioned in the "usage" page.
