### ISSUE TITLE
Fix BSVS model

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#136]
@lmaurits was looking into the parameter explosion with the BSVS model. He wanted to create an issue about it at some point, but it's definitely a thing that should go into 1.2.2, so I'll one now.

**Comment by lmaurits** [comment]
Making progress on this, but it's been slow going.  There were BSVS-related bugs in BEASTling _and_ BEAST which was preventing BSVS analyses from reliably starting in BEAST, and it took me a little while to disentangle where the problems were.  These are fixed now, i.e. BSVS analyses will at least start with no problems.  The parameter explosion is a separate issue.  I think I'm close to a fix on that, too, but need to do a little more testing.

**Comment by lmaurits** [comment]
Parameter explosion appears solved, but there are still frequent complaints from BEAST about having to scale to avoid instability.  I know there is a way to specify an alternate eigendecomposition class which is more stable.  Before closing this, I'll add in an option to support this (for BinaryCovarion, too).

**Comment by lmaurits** [comment]
Closing, which should have happened a long time ago.  There is an option to specify robust eigen decomposition implemented in BaseModel now, so we're now doing the best we can in this regard.
