### ISSUE TITLE
macroareas test config does not exist

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#139]
[beastrun_tests](https://github.com/lmaurits/BEASTling/blob/master/tests/beastrun_tests.py#L65) references tests for macroareas, with some specific ideas of how they should work:

        # Test below has calibration on Austronesian, but macroareas=Africa,
        # resulting in an emtpy calibration, which is the point of the test
        ("admin", "mk", "calibration", "macroareas"),

Actually, we have no such configuration file, and we never noticed because nonexisting config files were just ignored by `ConfigParser.read`.

**Comment by Anaphory** [comment]
The config file is called `macroarea.conf`, without `s`.

**Comment by lmaurits** [comment]
I renamed the file to `macroareas.conf` (with an `s`) rather than changing the test to look for `macroarea.conf` because the actual parameter in the configuration is `macroareas =` and it seemed best to match that.
