### ISSUE TITLE
Ancestral State Reconstruction: Restrict to subset of nodes

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#145]
Without having looked at the logistics: It should be made possible to reconstruct ancestral states only in certain nodes, to reduce disk space used.

This may require some kind of syntax to specify MRCA nodes again, which should not differ too much from other MRCA specifications.

**Comment by lmaurits** [comment]
It looks like the `AncestralStateLogger` class in BEASTLabs (as opposed to the `AncestralStateTreeLikelihood` class in beast-classic which we currently use for ASR) makes this quite painless, which is nice!  What's not nice is that I have no real idea what the differences/similarities are between these two classes, and whether we need to use both of them at different times to get our desired behaviours, or if one class can handle everything (I _suspect_ the former, but could be wrong).  Hopefully we can abstract all of this away from BEASTling users.

**Comment by Anaphory** [comment]
`AncestralStateLogger` looks it can log exactly one single MRCA reconstruction value for the entire tree.

`AncestralStateTreeLikelihood` is a thing that feels compelled to log the ancestral state for each and every internal node, plus the tips you ask it for.

Now I would like to inspect the ASRs in precisely 3 nodes. It looks like I would have to construct a separate `ASL` for each of them, with only one contributing to the likelihood. This is already suboptimal for the case I'm interested in due to the redundancy involved; if I did care about the co-dependencies of the three different reconstructions and which ones can occur together, I would be better off using an `ASTL` and using stream-editing methods to reduce it to the nodes of interest.

The `sample()` method of the `ASL` looks like it could reasonably support looking at the ancestor of more than one `TaxonSet`, do I want to get involved in Beast programming to write that?

**Comment by Anaphory** [comment]
I have put something together that can possibly do ancestral state reconstruction on multiple nodes in Beast. (One purpose of this was to see how `AncestralStateLogger` works before I go and use it.)

It's on https://github.com/Anaphory/statereconstruction and it essentially consists of minor changes to beastlab's AncestralStateLogger to support logging multiple MRCA nodes at the same time.

In the BeastXML interface, the only things changed are the name (currently `lucl.statereconstruction.AncestralStatesLogger` – mind the plural! – instead of `beast.evolution.likelihood.AncestralStateLogger`) and the type of the taxonsetInput, which now allows for more than one taxonset to be specified. If Taxonsets are specified in `<taxonset idref="...">` tags, this should be a generalization, not a change; I don't know how that works with `taxonset="@…"` attributes on the main object.

So for the moment, I will try to get BEASTling to work with in principle arbitrary number of specifications, but I will use BEASTlab's AncestralStateLogger and throw errors if more than one MRCA was specified.
I'm not sure about the best way to get statereconstruction into CBAN, given Remco's dislike of small packages.

**Comment by Anaphory** [comment]
Now, similar question to #168 but from the other side: How should the specifications of ancestors look like in Beastling? Should we expose “MRCA's ancestor” logic?

**Comment by lmaurits** [comment]
> AncestralStateLogger looks it can log exactly one single MRCA reconstruction value for the entire tree.

Do you mean it can log reconstructed values at precisely one tree node, can log reconstructed values for precisely one feature, or both?

**Comment by Anaphory** [comment]
It can log reconstructed values for precisely one tree node. It will, for that tree node, which is specified as the MRCA of a <taxonset> (or parent thereof), reconstruct each feature that belongs to its alignment – because it's still a drop-in replacement for TreeLikelihood.

So, when our alignments are per-meaning, each AncestralStateLogger can reconstruct exactly one meaning for exactly one MRCA of a given taxonset – my default test case right now is to specify all taxa, so I get the ASR of the features I specify in the root.

**Comment by lmaurits** [comment]
Right, sorry, I forgot it was s drop-in replacement for TreeLikelihood (the name makes it sound like it just logs).

**Comment by Anaphory** [comment]
Yes. It's a `TreeLikelihood` with special behaviour under logging.

**Comment by lmaurits** [comment]
You may well be able to just get your change accepted as part of the existing class in BEASTLabs, it can't hurt to try.  This would let us release support for reconstruction at a single node in 1.4.0 (throwing an error if more than one is specified), and then remove the restriction in a subsequent release after the next BEASTLabs release which just doesn't throw the error.

**Comment by Anaphory** [comment]
Sounds good! I will try that.

**Comment by Anaphory** [comment]
```
[language_groups]
alorese = alor1247-baran, alor1247-munas, alor1247-panda, alor1247-besar
[model vocabulary]
reconstruct = sky, sun, eye
focus = alorese, root
```
Is that a reasonable name for the property of language groups whose ancestors should be reconstructed? I did not go for something more specific like `reconstruct_at` because there may be other things we might want to focus on in a model apart from ASR, but I don't have concrete examples yet.

I admit it doesn't say in the name that it's a specification of nodes in the tree by them being MRCAs of language_groups.

**Comment by Anaphory** [comment]
WRT #128: Maybe `*` would be the switch for “Do ASR on the whole tree”?

**Comment by lmaurits** [comment]
> I did not go for something more specific like reconstruct_at because there may be other things we might want to focus on in a model apart from ASR, but I don't have concrete examples yet.

What if I want to do two or more of these other things with different MRCA sets?

**Comment by Anaphory** [comment]
Someone might, but then why are they running all their hypothesis tests in a single analysis?

We are both talking very hypothetically here, and I'm fine with it being decided one way or another, but I want that decision explicitly.

**Comment by lmaurits** [comment]
Alright, well, first of all, there are two issues here, I think.  One is how to specify arbitrary sets of languages to reconstruct on (i.e. how to bind names like "alorese" to taxonsets) and the other is what to call the property inside of `[model]` which consists of a list of those bound names specifying where to reconstruct.  These are separate decisions, so let's keep them to separate threads (#168 and here) and separate PRs.

So the question relevant to this Issue is "do we like the name `focus` and if not what's better", right?

I think I would prefer `reconstruct_at` or `reconstruction_points` or something like that which is more explicit and self-documenting about what it's for.  One of our design criteria should be that config files should make good intuitive sense when read by new users who don't already know all the magic words, and `focus` fails that test pretty hard, IMHO.

(if other things fail that test that I've failed to complain about, feel perfectly free to call me out on them)

**Comment by Anaphory** [comment]
Thou spakest truly, so I have changed the name in my samples to `reconstruct_at` (already a while ago, but I may or may not have pushed that yet.)

**Comment by Anaphory** [comment]
This is mostly resolved now, it just needs to be documented.
