### ISSUE TITLE
Specification of taxonsets for calibrations is too permissive

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#146]
The idea is that you can pass `Configuration.get_languages_by_glottolog_clade` a comma-separated list of "things", and get back a list of languages in the analysis satisfying the condition that one of the listed "things" is an ISO code or Glottocode for one of the languages _or_ the name of a Glottolog tree node which contains one of the languages.  You can even mix and match these two ways of specifying languages.  This facilitates nice and superficially user-friendly calibration specs like:

```
Germanic = normal(x,y)
Celtic,Italic,Germanic = normal(w,z)
eng,deu,nld = normal(a,b)
Celtic,Italic,eng,deu,nld = normal(c,d)
```

The problem arises when languages get included spuriously due to this "match anything" approach.  I just tried to define a large subset of Indo-European with a comma-separated list of ISO codes.  One of the languages was Belarussian, with ISO `bel`.  Unfortunately, "Bel" is also the name of a sub-sub-sub-...-sub-family of Austronesian (Glottocode `bell1262`), so two Austronesian languages got pulled in as well, violating monophyly constraints and leaving me scratching my head for a bit.

Not sure what the best approach is here, but it's clear that right now we are too permissive and sometimes languages get pulled into calibrations unexpectedly.

**Comment by Anaphory** [comment]
I suggest the following.

 - Give that function three switches that allow/forbid pulling in that type of clade.
 - Disable the default of finding nodes by names, there are probably other disambiguities in the Glottolog tree. Language names are just not guaranteed to be unique. And given that the user might need to know that it's `Kui (Indonesia)` as opposed to `Kui`, they might as well take kuii1253. (Once we find a clean way of distinguishing – eg. capital letters? – we can put it back in.)
 - Increase logging so that every call tells you what it pulled in.

**Comment by lmaurits** [comment]
I am really reluctant to disable finding nodes by name, we sold this as a big part of the user-friendliness of BEASTling in the paper and rightly so I believe.  This approach makes it very easy to write and more importantly read calibrations.  If I want to put a calibration on the age of Austronesian, I don't so much have to mind looking up `aust1307`, but if someone is reading my config and sees that, unless they're Robert or Harald they're going to have no idea what it is.  Austronesian?  Austroasiatic?  God help you if you are calibrating both families.  The Zen of BEASTling inherits "Readability counts" from the Zen of Python!

**Comment by lmaurits** [comment]
The motivating bug for this issue involved "bel" being both an ISO code _and_ a Glottolog name for a non-leaf tree node.  That _particular_ bug is actually very easy to fix.  I just pushed a fix so that each term in the comma-separated list is first compared against the language identifiers used in the datafile (ISO codes in my case), and if a match is found that term is removed from the list so that nothing in Glottolog can ever match against it.

This solves the issue of ISO codes colliding with named Glottolog nodes.  I assume analogous collisions with Glottocodes don't happen because of the numeric part of Glottocodes.

@xrotwang Are the names of Glottolog nodes guaranteed to be unique by any chance? 🤞

**Comment by xrotwang** [comment]
@lmaurits There's a policy to enforce uniqueness of names. This policy hasn't been enforced yet down to the dialect level, though. We should be there with the next release of Glottolog. @xflr6

**Comment by lmaurits** [comment]
Okay, I think I'm going to close this.  The immediate known bug has been fixed, the remaining possibility for collisions is pretty slim (especially if people migrate away from ISO and toward Glottocodes in future), and it sounds like the Glottolog folks are endeavouring to remove that possibility.  Since this part of the codebase is slated for overhaul anyway ( #162 ) I don't want to spend lots of time coming up with a way to guarantee we dodge those rare remaining cases.
