### ISSUE TITLE
CLDF specs have changed

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#147]
While we were looking another way, CLDF specs have changed – in particular, instead of one spec for all data types, there are now different variants for word lists and structure datasets.

While we assume columns named `Language_ID`, `Feature_ID` or `Parameter_ID`, and `Value`, the actual [release of the CLDF β specs](https://github.com/glottobank/cldf/releases/tag/v0.4) from last February requires

 - For word lists: `ID`, `Language_ID`, `Parameter_ID`, some column that is not `Value` (which contains “the word form, the main value, for the given language and the given concept (may have different degrees of”. [sic]) for cognate sets
 - For structure datasets (where the example is … a word list?), some columns are necessary (presumably `ID`, `Language_ID`, `Value`, judging from context?) plus `Feature_ID`, but `Feature_ID` may contain `~`-separated dimensions of the feature.

When I started typing this issue and comparing our code and the CLDF specs, I thought this would require a significant edit, but actually this is hardly any change at all and just a reminder to keep checking CLDF regularly.

**Comment by xrotwang** [comment]
Yeah, looking at CLDF regularly and giving feedback is the price you pay for being the avantgarde or early adopters :)

**Comment by xrotwang** [comment]
see #154
