### ISSUE TITLE
BEASTling uses non-standard Beast classes

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#15]
BEASTling assumes classes like `AlignmentFromTrait`, `PrunedTree` or `SVSGeneralSubstitutionModel` are available, but does not tell me in the documentation that I should ensure certain packages need to be installed.

**Comment by Anaphory** [comment]
Are the corresponding packages even available through the Beauti package installer?

**Comment by lmaurits** [comment]
The documentation does actually indicate this, see the "Dependencies" section in docs/installation.rst.  The required packages are indeed available through BEAUti.  I agree that this is a pain and will catch some users out, but the BEAST core is sufficiently minimalist that I think this is unavoidable.  I have been thinking of having BEASTling explicitly list on stdout all of the packages which a produced XML are dependent upon, which will hopefully make this more obvious.  I'll leave this issue until I've added that change, so I don't forget.

**Comment by lmaurits** [comment]
When run with --verbose, BEASTling now mentions dependencies for (I think) all classes which are not in BEAST core, and hopefully only mentions them when they are included in the output.
