### ISSUE TITLE
Monophyly translation runs, but beast does not accept xml

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#152]
I just generated a beast xml file from

```
[admin]
basename = lessersunda_noproto_ratevariation_autocode

[languages]
exclusions = p-aust1307-abvd,p-aust1307-acd,p-cent2245-abvd,p-cent2245-acd,p-mala1545-abvd,p-mala1545-acd,hama1240,p-alor1249,p-timo1261,p-east2519,nan,pmpacd
monophyly_newick = tree-glottolog-newick-patched.txt
monophyly = True

[model lexicon]
model = covarion
data = auto_data.tsv
file_format = cldf
rate_variation = True
```

with a monophyly newick tree

     ((((((((keda1252-leuba:1,keda1252-leuwa:1)keda1252:1,(((((alor1247-baran:1,alor1247-pandai:1,alor1247-munas:1,alor1247-besar:1)alor1247:1)alor1251:1,(lama1277-pukau:1,lama1277-lewobN:1,lama1277-lewob:1,lama1277-lewog:1,lama1277-lewoi:1,lama1277-tanju:1,lama1277-bama:1,lama1277-ritae:1,lama1277-lewom:1,lama1277-baipi:1,lama1277-waiba:1,lama1277-botun:1,lama1277-horow:1,lama1277-waiwa:1,lama1277-watan:1,lama1277-lamak:1,lama1277-minga:1,lama1277-adona:1,lama1277-dulhi:1,lama1277-kiwan:1,lama1277-wuake:1,lama1277-imulo:1,lama1277-belan:1,lama1277-lewop:1,lama1277-lewot:1,lama1277-lewok:1,lama1277-lamal:1,lama1277-lamah:1,lama1277-lewuk:1,lama1277-ileap:1,lama1277-mulan:1,lama1277-clemb:1,lama1277-kalik:1,lama1277-paina:1,lama1277-merde:1,lama1277-lerek:1,lama1277-lamat:1,lama1277-lewoe:1)lama1277:1)lama1293:1)lama1292:1,(sika1262-maume:1,sika1262-tanai:1,sika1262-hewa:1)sika1262:1)sika1265:1)flor1239:1,((((tetu1245-suai:1,tetu1245-vique:1)tetu1245:1,tetu1246:1)tetu1244:1)cent2079:1,(((amar1273-kotos:1)amar1273:1)uabm1238:1)west2545:1)timo1259:1,((idat1237:1,laka1255:1)east2733:1,mamb1306:1,(kema1243:1,tuku1254:1)west2547:1)timo1260:1,p-cent2245-abvd:1,p-cent2245-acd:1)cent2245:1)cent2237:1,p-mala1545-abvd:1,p-mala1545-acd:1)mala1545:1)nucl1752:1,p-aust1307-abvd:1,p-aust1307-acd:1)aust1307:1,((((atim1239:1,abui1241-petle:1,abui1241-petle-o:1,abui1241-takal:1,abui1241-fuime:1,abui1241-takal-o:1)abui1241:1,(((kula1280-lanto:1)kula1280:1,sawi1256:1)tang1352:1,(kola1287:1,wers1238-marit:1)wers1238:1)kola1286:1,kama1365:1,(kira1248:1,kuii1253:1)kuii1253-x:1,((kafo1240:1,(kelo1247-bring:1,kelo1247-hopte:1)kelo1247:1)klon1234:1,(((adan1251-lawah:1,adan1251-otvai:1)adan1251:1,hama1240:1,kabo1247:1)adan1252:1,((baka1276:1,pura1258:1,blag1240-nule:1,blag1240-tuntu:1,blag1240-warsa:1,blag1240-bama:1,blag1240-kulij:1)blag1240:1,rett1240:1)blag1241:1)stra1245:1)west2787:1)alor1250:1,(kaer1234:1,kaer1234-o:1)kaer1234-x:1,nede1245:1,((dein1238:1,teiw1235:1)teiw1235-x:1)teiw1236:1,(lamm1241-westp:1)lamm1241:1,p-alor1249:1,alor1249-sar-a:1,alor1249-sar-n:1)alor1249:1,((buna1278-o:1,buna1278-malia:1,buna1278-suai:1,buna1278-bobon:1)buna1278:1,((fata1247:1)fata1246:1,maka1316:1)east2520:1,p-east2519:1)east2519:1,p-timo1261:1)timo1261:1)root:1;

but beast complains

```
java.lang.RuntimeException: Cannot find taxon tang1352  in taxon list
	at beast.math.distributions.MultiMonophyleticConstraint.parse(Unknown Source)
	at beast.math.distributions.MultiMonophyleticConstraint.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parse(Unknown Source)
	at beast.util.XMLParser.parseFile(Unknown Source)
	at beast.app.BeastMCMC.parseArgs(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)

Error 110 parsing the xml input file

validate and intialize error: Cannot find taxon tang1352  in taxon list

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='prior' spec='util.CompoundDistribution'>
                  <distribution id='constraints' spec='beast.math.distributions.MultiMonophyleticConstraint'>
```

**Comment by Anaphory** [comment]
This works without problems when the internal nodes of the tree have no names.

**Comment by lmaurits** [comment]
So basically this boils down to BEAST's Newick parser for monophyly constraints not being able to handle internal node names, right?  There's a good chance this also affects starting trees.  Maybe our `sanitise_tree` method, or whatever it's called, should just scrub internal node names?  This should not affect the intended behaviour for user-supplied starting or monophyly trees at all.

Unrelated note: assuming our newick parser _can_ handle this internal labels, that could be a an elegant way to specify non-Glottolog clade names to address #153....

**Comment by lmaurits** [comment]
Goodness we are a smart bunch of dudes, our Newick parser already has a `remove_internal_names` method, which should make this a one-line fix in BEASTling.  I'm going to update `sanitise_tree` right now.  It would be nice if you could test that this fixes the problem, but I suppose after several months you're unlikely to have this exact analysis lying around ready to roll?

**Comment by lmaurits** [comment]
Okay, we now scrub internal node names from starting trees and monophyly trees, and there are unit tests making sure that BEAST runs on the output when such trees are used.
