### ISSUE TITLE
Support geographical restrictions on clades without glottolog

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#153]
When languages are not in Glottolog, clades can be specified using the `monophyly_newick`. However, that tree is not permitted to contain clade names.

geo_priors, on the other hand, takes a comma-separated list of *clades*, and it is not possible to define such a clade using a beastling configuration file.

In the end, what I'm looking for is a way to set `allInternalNodes="true"` on the `<geoprior>` object of the root of the tree, to prevent all nodes from lying in the ocean. Because that makes this not just an enhancement – extension of existing functionality to work under new combinations of assumptions –, but a significantly feature request, this points also to the other feature request concerned with hacking beast xml using some kind of DOM notation in the beastling config – I thought we had a feature request for that, but I cannot find it righ now.

**Comment by Anaphory** [comment]
Oh, and there is actually a bug connected to this: Specifying individual *taxa* on the left-hand side of a `geo_prior` should not be permitted, because `ApproxMultivariateTraitLikelihood` runs into `NullPointerException`s in L.119/120.

**Comment by Anaphory** [comment]
Oh. Fiddling with BEAST xml for a bit returned the following result: The additional prior of “people don't live in the sea” is expressed by adding

```
 <distribution id="everywhere.geoPrior" location="@location.geo" spec="sphericalGeo.GeoPrior" tree="@Tree.t:beastlingTree" taxonset="@taxa" allInternalNodes="true">
   <region kml="KMLFILE" spec="sphericalGeo.region.KMLRegion" />
 </distribution>
 ```
to the *prior*, not to the `MultiGeoPrior` in the likelihood. (At least in that case the inference runs, I'll see whether it outputs something reasonable.)

**Comment by Anaphory** [comment]
Hm, no. That construction runs, but it does not prevent BEAST from placing nodes in the sea.

**Comment by Anaphory** [comment]
![migration](https://user-images.githubusercontent.com/1579723/26940935-e2a41098-4c7c-11e7-8d08-a6b73a0ee209.png)

**Comment by lmaurits** [comment]
One possible workaround to this would be to give BEASTling support for some discrete phylogeographic methods, i.e. methods where location is not represented by latitude/longitude but rather as a language simply being present in one of a pre-defined set of regions, which might be cities, countries or, in this case, islands. (or portions of larger islands).  Obviously there is some degree of information-loss involved here, but on the other hand there are some nice advantages too, one of them being that nobody ends up in the sea, another being that it's comparatively straightforward to build in some prior geographic information about e.g. plausible migration routes.

You could actually roll your own version of this with BEASTling 1.3.x, for experimenting.  Just make a one-feature data file and use BSVS to model it, with a separate clock from your language data.  If you used the dev branch you could turn on ancestral state reconstruction to estimate homelands.

If this became something officially supported by BEASTling in future, it would be nice, if it were feasible, to include some kind of automated partitioning into discrete locations using the Glottolog coordinates.  This would include packaging some kind of polygon datasets with BEASTling and probably a dependency on some kind of GIS library.  Could be quite heavy-weight, in which case I would be reluctant to include it, but we might be able to make it work.

**Comment by lmaurits** [comment]
I think the most useful interpretation of what this Issue wants is to basically give the user the ability to define their own non-Glottolog clade labels, which are then available for use anywhere else in the BEASTling config, e.g. for specifying monophly constraints (cf #151), for time calibrations, or for geographic calibrations (cf #150).

Possibly this could be done with a new section where each line defined a clade:

```
[clades]
foo_clade = glot0001, glot0002, glot0003
bar_clade = glot0004, glot0005, glot0006, glot0007, glot0008

```
Or it could done more succinctly with a `clade_definitions = /path/to/file` option in the existing `[languages]` section, where that file could either contain text like the clade section above or a Newick tree with internal node names.

**Comment by lmaurits** [comment]
Btw, regarding your initial motivating problem for this issue (`[geo_priors]` not accepting arbitrary clades): Geo priors uses exactly the same method to turn a (list of) clade name(s) into a bunch of languages as the temporal calibration system, so in a pinch you can always give it a comma-separated list of ISO or Glottocodes to define arbitrary clades for your dataset.  I fully acknowledge that this could be unwieldy for large analyses.

**Comment by Anaphory** [comment]
I'm back to trying things like this. Now … where did I have the code to generate the map up there?

**Comment by lmaurits** [comment]
Not sure, but if you find it and it was done in Python I'd be keen to see it.

**Comment by Anaphory** [comment]
I found it again. It's in the `geoplot` command of my `treesed` (because stream editor) fork of your `phyltr` command: [geoplot.py](https://github.com/Anaphory/treesed/blob/master/phyltr/commands/geoplot.py)

Note that that script is not very flexible yet.

**Comment by Anaphory** [comment]
This issue is confusing to me now, wanting to do too many things. I think one of them is addressed in #181.
The other one is
> hacking beast xml using some kind of DOM notation in the beastling config

which we informally discussed elsewhere and which should either be an explicit, separate issue or argued as undesirable.

**Comment by lmaurits** [comment]
Does this Issue still serve a purpose?  It seems like all the things it wants have either been split out into other Issues, or have been addressed by your addition of `[language_groups]`?

**Comment by Anaphory** [comment]
No, it does not.
