### ISSUE TITLE
Upgrade CLDF support to version 1.0 of the spec

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#154]
The [CLDF spec](http://cldf.clld.org/) has evolved quite a bit to version 1.0, which BEASTling should support. This may introduce some backwards incompatible changes. But maybe more importantly, considering that CLDF is now a more complex specification, BEASTling should use [`pycldf`](https://pypi.python.org/pypi/pycldf) to read CLDF data.

**Comment by Anaphory** [comment]
Now that I have a decent idea of CLDF, I might take responsibility for this for the future.

**Comment by lmaurits** [comment]
Have finally been reading up on the new CLDF spec and playing with pycldf.  Just making a few notes relevant to BEASTling:

- We should support some easy and sensible process for known borrowings in Wordlists with a Borrowing Table - replacing known borrowings with "?", perhaps?  We can discuss what best practice should be, but we should probably make it require a deliberate effort to produce an analysis where known borrowings are treated as genuine cognates.
- Some of the automagic surrounding binarisation of multistate data, and trying to decide whether the user has already done this or not, could probably be made more robust or at least more elegant if we pay attention to whether the data is a Wordlist or a Structure Dataset.

**Comment by lmaurits** [comment]
Bare minimum goals:

- [ ] Read data from a CLDF Wordlist or Structure dataset (I guess CLDF Dictionaries are of no interest to BEASTling?)
- [ ] Read language location data from CLDF metadata

**Comment by Anaphory** [comment]
Formally, language location data reading will need support of CLDF property URLs.

In lazy practice, I just changed the name of the `id` column in my LanguageTable to `Language_ID` and could then read the file als geo data without issues.

**Comment by Anaphory** [comment]
Wordlist and structure dataset reading will come shortly – Wordlists are already in develop, and I'm just writng tests.

**Comment by Anaphory** [comment]
Closed by #176
