### ISSUE TITLE
Use the rootHeight input on RandomTree

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#163]
The RandomTree tree initialiser has a rootHeight input I never noticed before, which lets you specify the root height of the starting tree (if it is compatible with constraints).  I have had analyses start of with absurdly high root heights before and it can take surprisingly long to bring them down, I guess because lots of parameters have to move in concert.  We should come up with some very rough rule of thumb to estimate a sensible root height (i.e. plus or minus an order of magnitude or two) based on calibrations and start off there.

**Comment by lmaurits** [comment]
Done, and not even that hackishly!  I used language counts and the midpoints of calibrations with finite endpoints to make multiple estimates of the Yule birthrates, found the mean birth rate estimate and the corresponding expected tree height, and used these as initial values.  Tested it on 3 real analyses and got quite decent estimates.

That was fun!

**Comment by Anaphory** [comment]
That sounds really awesome!

**Comment by lmaurits** [comment]
I am hoping that at some point we can include a lot of this kind of intelligent initialisation stuff in BEASTling, especially with regard to trees.
