### ISSUE TITLE
Repository permits pushing to development branch without testing first.

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#169]
I just pushed to this repository when actually I wanted to push to my own fork.

It went through without complaints.

Please protect pushing to `develop` in the same fashion as merging pull requests are tested and as (hopefully) pushing to the `master` branch is prohibited.

**Comment by Anaphory** [comment]
For reference: #165 was the pull-request that got merged without sufficient test coverage.

**Comment by lmaurits** [comment]
Alright, I think I've done this now?  Enabled "Require status checks to pass before merging" for both master and develop.

**Comment by lmaurits** [comment]
Do you want to try to reverse that merge, or just fix whatever problems there are with it in develop?  Do you need me to do anything to facilitate fixing this?

**Comment by Anaphory** [comment]
There are three things to that merge:
 - Merging `master` into `develop`, because they had separated surprisingly far;
 - Initial CLDF support;
 - Being more verbose about ASR.

All tests had succeeded, the CLDF support needs improvement and test coverage. Given that, I myself would be happy to fix these things inside `develop`.

**Comment by lmaurits** [comment]
Okay, great!  Time to close this?
