### ISSUE TITLE
CLDF metadata-free wordlists – Cognate column?

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#175]
CLDF metadata-free wordlists, that is, loading data from a `forms.csv` and not a `Wordlist-metadata.json`, do not have well-defined semantics for cognate columns.

Do we want to use the same logic as we did for pre-1.0 CLDF and permit the user to specify the name of a column that should be interpreted as cognate sets?

**Comment by xrotwang** [comment]
Hm. We could match any column name against the preferred labels of
properties in the ontology. So Cognateset_ID would be recognized also in
forms.csv.

Am 27.10.2017 18:27 schrieb "Gereon Kaiping" <notifications@github.com>:

**Comment by Anaphory** [comment]
The one given here?
https://github.com/glottobank/cldf/blob/ff33e40dbccabaf1191f08eb8f486a13343a6f5b/terms.rdf#L238
That sounds like a reasonable fallback.

https://github.com/lmaurits/BEASTling/blob/61029c48135c5e3f5b1fd73a1e6d3709d4e36a00/beastling/fileio/datareaders.py#L11
We do have infrastructure (`value_column=…`) for specifying a non-standard column, would there be any reason to *not* provide that functionality for metadata-free or metadata-packaging data sets?

**Comment by Anaphory** [comment]
I have now re-used the `value_column` property.
