### ISSUE TITLE
Fix clldutils dependency

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#182]
I just released a backwards incompatible version 2.0 of `clldutils`. Thus, the [dependency in BEASTling](https://github.com/lmaurits/BEASTling/blob/affdd4e7c3d0c521f3e398a2c3b841848fa780ea/setup.py#L15) must be either pinned to 1.14, or set to a [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release), i.e. `~=1.13`.

**Comment by xrotwang** [comment]
Sorry, to introduce this bug somewhat deliberately. But switching to compatible release specifiers for dependencies may make sense in general.

**Comment by xrotwang** [comment]
Note that we moved the `dsv` module and the CSVW support to its own package [`csvw`](https://pypi.python.org/pypi/csvw).

**Comment by Anaphory** [comment]
I think these incompatibilities have been quietly fixed in the development branch, so we should now require `~=2.0`.
