### ISSUE TITLE
In tests: “ERROR: BeastRun with admin mk monophyletic geo geo_prior”

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#188]
One test for the unification of `language_group`s fails with 

```
ValueError: Language group or Glottolog clade afad1236 not found or was empty for the languages given.
```

The fact that it's that BeastRun reminds me of the previous strange issues, so I'm not convinced this is what's actually going on.

**Comment by lmaurits** [comment]
Does this have anything to do with the ASR tests?  Those still fail for me, locally, although Travis seems happy, which is baffling and concerning.

**Comment by lmaurits** [comment]
Hold onto your hat: I think something is screwy with the code that tells us *which* test has failed when a failure occurs.  More to follow after lunch...

**Comment by Anaphory** [comment]
In most cases the report which test failed is correct, but there is one fringe case which has to do with the way beastrun tests are defined and which does report nonsense, I think.

I'm also checking how tests behave on the Anaphory/BEASTling/language_groups branch. (This is where the error mentioned above was last seen.) I would like language_groups to pass testing so I can pull-request it for 1.4.0 – modulo writing documentation.

**Comment by lmaurits** [comment]
Or maybe before lunch.  Look, I don't know *why* or *how*, but after some experimenting I can confirm that sometimes the tuple of config files which is reported as causing a failure is actually the tuple which comes *after* the genuine failure case in the big list.  Which means “ERROR: BeastRun with admin mk monophyletic geo geo_prior” actually means “ERROR: BeastRun with admin mk monophyletic geo geo_sampled” (last config differs).

**Comment by Anaphory** [comment]
In my nosetest 1.3.7, I tend to get the last entry (“ERROR: BeastRun with admin mk monophyletic geo geo_prior”) in every case, the actual test case failing has to be `("admin", "mk", "calibration_tip_originate")` because none of the other tests reference `afad1236` as clade. (CLDF tests have that tip.)

**Comment by lmaurits** [comment]
At my end, BEASTling and BEAST are both perfectly happy with `("admin", "mk", "calibration_tip_originate")`.

**Comment by Anaphory** [comment]
They should be. It fails in my `language_groups` branch, because the clade `afad1236` is empty, and that's not a thing BEASTling complains about currently, but I have added tests that clades should be non-empty, so when the new language_groups logic encounters

    originate(afad1236) = 1223-1224

it finds an empty clade. I should check the `git blame` for that line to see whether that's my fault, as well.

**Comment by lmaurits** [comment]
Does my `develop` branch test clean for you, including beastrun tests?

**Comment by Anaphory** [comment]
Yes, the current tip of develop runs very cleanly apart from the one test where the return value of the `beast` call is supposed to be 4 but comes out as 2, which is probably the way I wrote my `~/.local/bin/beast`.

**Comment by lmaurits** [comment]
Ah, good!  So it's only failing at my end because I don't have your ASR stuff.

I didn't realise we ever checked for particular return codes?

**Comment by Anaphory** [comment]
Wait, I should say that they did run nicely on the laptop, which may or may not have yet another configuration of `nosetest`. I'll start a test on your development branch on the workplace desktop, just for good measure.

**Comment by Anaphory** [comment]
Apparently, here I haven't installed the current version of `beast` and `AncestralStatesLogger`, either, but I *do* get the correct test identifiers printed in the failure log. As said, this is nosetests 1.3.7, which was installed from the Ubuntu package sources.

And the error code is from the beastling cli, not from beast as I thought. Hm.

```
======================================================================
FAIL: Test the root ASR output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vol/home/kaipingga/beasties/BEASTling/tests/beastrun_tests.py", line 149, in _do_test
    stderr=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['beast', '-java', '-overwrite', '/tmp/tmpg6at3_l2/test']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/home/kaipingga/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/vol/home/kaipingga/beasties/BEASTling/tests/beastrun_tests.py", line 171, in test_asr_root_output_files
    ), inspector=assert_asr_logfile)
  File "/vol/home/kaipingga/beasties/BEASTling/tests/beastrun_tests.py", line 154, in _do_test
    config_files, e.returncode))
AssertionError: Beast run on ('admin', 'mk', 'ancestral_state_reconstruction', 'ascertainment_false') returned non-zero exit status 1

======================================================================
FAIL: Test the clade ASR output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vol/home/kaipingga/beasties/BEASTling/tests/beastrun_tests.py", line 149, in _do_test
    stderr=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['beast', '-java', '-overwrite', '/tmp/tmpg6at3_l2/test']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/home/kaipingga/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/vol/home/kaipingga/beasties/BEASTling/tests/beastrun_tests.py", line 242, in test_asr_clade_output
    _do_test(("admin", "mk", "ancestral_state_reconstruction", "taxa", "reconstruct_one"), inspector=assert_asr_logfile)
  File "/vol/home/kaipingga/beasties/BEASTling/tests/beastrun_tests.py", line 154, in _do_test
    config_files, e.returncode))
AssertionError: Beast run on ('admin', 'mk', 'ancestral_state_reconstruction', 'taxa', 'reconstruct_one') returned non-zero exit status 1

======================================================================
FAIL: test_generate_errors (tests.cli_test.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vol/home/kaipingga/beasties/BEASTling/tests/cli_test.py", line 62, in test_generate_errors
    self._run_main(config_path('no_data', bad=True), status=2)
  File "/vol/home/kaipingga/beasties/BEASTling/tests/cli_test.py", line 42, in _run_main
    self.assertEqual(context.exception.code, status)
AssertionError: 4 != 2
```

**Comment by lmaurits** [comment]
The correct test identifiers is not too surprising, as the ASR tests are done separately from the big long list of configs.  I see those ASR failures, and a few more too, I think.  I don't recognise the 4 != 2 error, I'm running things again now.

**Comment by Anaphory** [comment]
After updating the `beast2` and `statereconstruction` Beast addons to their most current state, the

```
======================================================================
FAIL: test_generate_errors (tests.cli_test.Tests)
----------------------------------------------------------------------
AssertionError: 4 != 2
```

is the only problem I see in `develop` also on this machine.

**Comment by lmaurits** [comment]
Why the flip don't I see that error?

**Comment by Anaphory** [comment]
![Elefino](https://www.explainxkcd.com/wiki/images/9/9b/elefino.jpg)

I mean, travis does not see it either; I see it in all 3 of my instances.

**Comment by Anaphory** [comment]
That error has now vanished for me on at least one machine, it appears.

**Comment by lmaurits** [comment]
Well, I suppose that's progress, even if it is non-deterministic.

I'm still seeing “ERROR: BeastRun with admin mk monophyletic geo geo_prior” failures, which is what this Issue is supposed to be about.  Do you know the root cause of this yet?  Can I help in any way?

**Comment by Anaphory** [comment]
I have absolutely no idea.

**Comment by lmaurits** [comment]
Okay, this is weird.  BEASTling generates an XML for those configs just fine.  When I try to run that XML on my laptop I get weird X11 errors, as if BEAST is trying to pop-up a GUI window.  When I try to run the same XML ssh'ed into a remote machine, it runs just fine and returns without error.

**Comment by xrotwang** [comment]
It would be a pity if GUI awareness was built into BEAST so deeply that BEASTling isn't enough to turn it into a proper library.

But I also hope that it isn't any of the test scaffolding - redirecting streams, caching stuff between tests, etc. - that's getting in the way of debugging here.

**Comment by lmaurits** [comment]
Alright, just confirmed that all tests run clean for me on my laptop *if* I run them from a virtual terminal (i.e. the thing provided by the Linux kernel) but give this message on the exact same machine if run from a terminal emulator (i.e. a thing running in X).  So something X related is going on here, for sure.

Looking at the source code for the `KMLRegion` object that BEAST uses, yeah, it does seem to actually use some graphical stuff.  Most of it appears to be either commented out or hidden inside `if(debug) {` switches.  It seems like you can get it to spit out .png maps of your regions and language points if you want to, presumably to help track down problems.  It might be the case that this library wants X to be running even if it doesn't actually open any windows.  This is not too uncommon, e.g. even matplotlib has this kind of problem.

The only question is why this is failing now, when I have *always* developed BEASTling on a machine with X running.  Well, in my case right now "my laptop" above actually means "in a Linux VirtualBox machine running inside my sadly-Windows-based university-issued laptop", and I *have* previously mucked around with all kinds of `.Xauthority` voodoo to try to work around the above-mentioned matplotlib issue, back when I was trying to keep this VM a pure framebuffer machine.  So I would be inclined to write this off as some quirk of my recent new X environment, except for the fact that @Anaphory sees it too.

**Comment by Anaphory** [comment]
Currently, I don't have *any* errors. The last error that vanished for not-apparently-deterministic reasons was the `FAIL: test_generate_errors (tests.cli_test.Tests): AssertionError: 4 != 2` one.

That `BeastRun with admin mk monophyletic geo geo_prior` threw `ValueError: Language group or Glottolog clade afad1236 not found or was empty for the languages given.`, which started this issue, was entirely justified and has been fixed.

In the past, I had a single misattribution of `BeastRun with admin mk monophyletic geo geo_prior` failing (or erroring) where that test itself appeared also elswhere in the log; I think that error vanished when I updated `nosetest`, but is still a mystery to me.

**Comment by lmaurits** [comment]
Oh, this _is_ just me!  I might try restarting X or even the whole VM and see if this goes away...

**Comment by Anaphory** [comment]
I'm just running `nosetests` on a tty with no X. I'll tell you what comes up.

**Comment by lmaurits** [comment]
Okay, I stopped X, removed all X-related dotfiles, rebooted the machine and tried again.  I no longer see the error I was seeing, so I guess I was right about transient X environment gremlins.

**Comment by lmaurits** [comment]
So this Issue no longer describes any genuine, reproducible problems, is that right?

**Comment by Anaphory** [comment]
Right.
