### ISSUE TITLE
Approximate frequencies and rounding issues

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#194]
What's going on in https://github.com/lmaurits/BEASTling/blob/258cedb068c25b7de845681ff4af2306e20bd6e2/beastling/models/mk.py#L49
and why is that ever a useful setting? There is always chance that some frequencies round to zero, leading to impossible configurations; rounding to 1 digit is very arbitrary, and if it does not succed (eg. for 6 equally distributed values) the whole method breaks at an assertion.

**Comment by lmaurits** [comment]
The original motivation was to increase the probability of different features ending up with identical frequency vectors (e.g. two binary typological features which happened to have empirical distributions (0.32, 0.68) and (0.34, 0.66) would both map to (0.3, 0.7)), which would then let them share the same substitution model objects, making the XML smaller and in theory making the analysis run faster and use less memory (and BEASTling is supposed to recognise and automatically make use of this possibility, or at least that was the goal).  Simply rounding to 1 digit is _not_ the best way to encourage these frequency collisions, I agree.

**Comment by Anaphory** [comment]
Ah! If I have a good idea how to deal with this, I'll implement it; for the moment I have only fixed the issue that frequencies might not add up to exactly `1` by only requiring that they are within 1±1e-10.
