### ISSUE TITLE
Taxon sets of starting trees are not vetted for compatibility with data

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#20]
The starting_tree= option in a [model] section allows the user to specify a starting tree.  If the taxon set of that tree does not perfectly match the taxon set of the data (after applying family filters, throwing out languages with no data, etc.), then BEAST will not run the resulting analysis.

Ideally, BEASTling should extract the taxon set from a provided starting_tree and compare it against the data.  If the data contains languages which are not in the tree, this pretty much has to be a fatal error.

If the starting tree contains languages which are not in the data set, but all languages in the dataset are present, ideally BEASTling should prune the starting tree to match.  This facilitates, e.g, using published reference trees for large families with datasets which may not contain 100% of the languages in that family.  This requires either writing a Newick parser, or becoming dependent upon an existing one (ete2?).

**Comment by lmaurits** [comment]
The starting tree is also not tested for compatibility with monophyly constraints, if those are imposed.

**Comment by lmaurits** [comment]
All of this is now handled except for the monophyly constraint compatibility testing.

**Comment by Anaphory** [comment]
Should this not behave according to `overlap`, using `union` or `intersection`? (Maybe that option should be extended by a default value throwing an error)
I still have one big file of features, which I want to graft on a tree, using only the feature values for the languages actually in the tree – a case you dismiss as a fatal error. If I could just rely on `intersection` handling, that would be fine.

**Comment by lmaurits** [comment]
I am entirely open to extending the handling of starting_trees.  That said, I also recently added a "languages=" option in [languages], which lets you give either a comma-separated list or a filename for a file with one language per line, specifying a list of languages, and any additional languages in the data will be ignored (it is quite analogous to the "families=" feature, just more fine grained).  If you have a tree you want to use, you could just put the leaves of that tree in a file and use this.  In fact, this is exactly what we do in the Austronesian example in the [BEASTling paper](https://github.com/glottobank/BEASTling_paper), to choose only the languages in WALS which are on Simon's tree.  But admittedly it would be nice not to have to do this.

**Comment by Anaphory** [comment]
It looks like the pruning through "languages=" is applied _after_ the data files are loaded and interpreted, so that my code reports features set to `X` (invalid) in my WALS table, but no `X` appears in the generated alignment. (It does not help that I seem to have too many incompatible ways to guess about ambiguous characters, otherwise I might not have noticed.)
