### ISSUE TITLE
Remove the dependency on clldutils

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#243]
The only thing `beastling` needs from `clldutils` is the `INI` class - which is a rather small extension of `configparser.Confiparser`. It's main usefulness came from the fact that it abstracts away the py2 compatibility issues. Now that we are on py2, we could ged rid of this.

**Comment by lmaurits** [comment]
Well, this *would* allow us to adopt `attrs` without a net increase in dependencies, which is always a good thing to push back against, IMHO.

**Comment by xrotwang** [comment]
Ah yes, it will decrease dependencies quite a bit - although I tried to keep the dependencies of `clldutils` sane, no `rdflib` or `ete3` or similar.
