### ISSUE TITLE
Support Glottolog releases

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#27]
BEASTling should have support for Glottolog releases, i.e. it should be possible to specify a particular Glottolog release in the configuration from which to use the classification. The classification of the latest Glottolog release (or of all previous releases) available for a BEASTling release should be distributed with the BEASTling package, and specifying a more recent release should result in downloading the new classification, possibly to a BEASTling [user cache dir](https://pypi.python.org/pypi/appdirs/1.4.0).

**Comment by lmaurits** [comment]
It's probably obvious, but just to be clear: I think the option specifying a particular Glottolog release should go in the [admin] section.

**Comment by lmaurits** [comment]
What's the status of this?  I tried testing it this morning by running a config with glottolog_release=2.6, but it errors out.  It looks like the http://glottolog.org/static/download/x.y/tree-glottolog-newick.txt resources don't exist yet?  Not trying to rush you, I'm just going through and closing finished Issues this morning and was trying to get a sense for how complete this is.

**Comment by xrotwang** [comment]
I noted in the docs that this only works for Glottolog >= 2.7 - which at the moment means just the version distributed with BEASTling. I can't get access to the server from here, so I can't upload newicks for older versions. As it is right now it will work with Glottolog 2.8, though :)

**Comment by lmaurits** [comment]
Do you mean that http://glottolog.org/static/download/2.8/tree-glottolog-newick.txt is supposed to exist right now?  Or just that it will be automatically generated when 2.8 is release?

**Comment by xrotwang** [comment]
It will be created when Glottolog 2.8 is released and by then will be downloadable by BEASTling. 2.8 isn't out yet.

**Comment by lmaurits** [comment]
Right, got it.  So basically the feature is fully implemented, but the downloading of versions not packaged with BEASTling cannot be properly tested yet (i.e. using an actual HTTP request instead of a mocked up one) due to non-availability of old files because you can't get to the server?

**Comment by xrotwang** [comment]
Genau!

**Comment by lmaurits** [comment]
Alright, I will close this then since the feature is implemented, but I look forward to doing a "real" test once you get access to the server again. :)
