### ISSUE TITLE
Inconsistent naming of `monophyly` settings

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#30]
To configure monophyly constraints, a setting `monophyly` or `monophyletic` can be specified (`monophyletic` is [documented](https://beastling.readthedocs.org/en/latest/config.html#languages-section)). But the additional settings `monophyly_grip`, etc. are not accepted in the `monophyletic_*` variant.

**Comment by lmaurits** [comment]
I decided that I am okay with allowing both monophyly=True and monophyletic=True (both are now documented).  It's a similar kind of userfriendliness to accepting binarised or binarized.  I don't see it as a big problem that the others accept only monophyly_, as the monophyletic_ versions sound very unnatural to me as a native speaker.
