### ISSUE TITLE
python 2 + 3 support

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#33]
It would be nice if BEASTling could be run with both python 2.7 and python >= 3.4.

**Comment by lmaurits** [comment]
Agreed (although, I'm curious, what's the reason for starting py3 support at 3.4?).  I know you said that 100% test coverage is generally a good idea before attempting a conversion.  Yesterday I installed "coverage" (nice tool I didn't know about before) to see where we are falling short in this regard.  It doesn't look like it will be too hard to rapidly increase the coverage, so I'm going to spend some time on this today.

**Comment by xrotwang** [comment]
It is kind of generally accepted to only start py3 support at 3.3. All my software starts with 3.4 because that's the py3 distributed with ubuntu 14.04. Considering that there's already py 3.5, I'd think that supporting < 3.4 may be not very useful anymore.

**Comment by lmaurits** [comment]
I'm actually not very good at it, but in general when writing software for general consumption I try to support older versions if it is not too arduous.  I have previously been stuck using university computers with 2.6 installed and I've not had root access to do an upgrade, so I know the pain of being left behind.

I'm going to start working on the test coverage after this coffee break.

**Comment by xrotwang** [comment]
Ok. Thanks to `tox` it shouldn't be too hard, to throw py 3.3 into the mix. py 2.6 and py < 3.3 I'd consider too different to try to support. (E.g. I wouldn't want to do without [`argparse` and `OrderedDict`](https://docs.python.org/3/whatsnew/2.7.html).)

**Comment by lmaurits** [comment]
Sure, I think these days I am finally okay with leaving 2.6 behind.  In the past, I have lived without argparse - in fact, I once even lived without optparse and used getopt!

I just did a push with some test coverage improvements.  Still not all the way there yet, but for now I want to switch to more important work on the BEASTling paper.  I will probably play with it some more tonight.  Getting everything above 90% at least by the end of the day should be a realistic goal.

**Comment by xrotwang** [comment]
cool. I can add integration with [tox](https://testrun.org/tox/latest/), to have a more standardized way to test compatibility across python versions.

**Comment by SimonGreenhill** [comment]
Great, I was going to work on py3 compat but can't easily test on a 2.7 environment, so a tox would make that easier.

**Comment by lmaurits** [comment]
Okay, I did a little more work on the tests while I rerun the paper's example IE analysis (with known borrowings excluded) and Austronesian analysis (with features which are more than 33% missing data excluded).  We are now at 90% or higher coverage for every file, and have 93% coverage in total.

I have added the three major new features that I wanted for 1.2.0.  Robert, are there any more significant refactorings that you need to do for the improved Glottolog support?

If most of the dust on new features has settled, I think it's probably safe for people to start experimenting with py3 conversions now.  Yes, some conversion bugs may lurk behind the untested 7% of the code, but this is no more likely than entirely non-py3-related bugs lurking in the same place, so the risk to users is users is minimal.  I will continue to work on test coverage throughout the week, anyway.

**Comment by xrotwang** [comment]
@lmaurits I submitted basic Glottolog release support as PR, I think that's good for 1.2.0. Started work on py3 support in a separate branch.

**Comment by lmaurits** [comment]
PR accepted, with thanks!

**Comment by xrotwang** [comment]
@lmaurits I'm running into a [sorting issue when porting to py3](http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp). In `make_tight_monophyly_structure` a structure like the one in the example below is sorted, which fails in py3. Is this sorting necessary? If so, we'd have to recreate the expected behaviour as callable to pass into `sorted` as `key` argument.

``` python
(beastling)robert@astroman:~/venvs/beastling/BEASTling$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> l = [[[u'abf'], [u'kbt']], [u'aas'], [u'abg'], [u'aiw']]
>>> 
>>> 
>>> sorted(l)
[[[u'abf'], [u'kbt']], [u'aas'], [u'abg'], [u'aiw']]
>>> 
(beastling)robert@astroman:~/venvs/beastling/BEASTling$ python3.4
Python 3.4.1 (default, Jul  7 2014, 09:21:41) 
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> l = [[[u'abf'], [u'kbt']], [u'aas'], [u'abg'], [u'aiw']]
>>> sorted(l)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: str() < list()
```

**Comment by lmaurits** [comment]
Haha, how annoying that a significant porting issue is coming from such a silly feature that I haven't even documented it.  I would consider gettting rid of these (and would definitely change the "tight"/"loose" naming convention) if it wouldn't mean either breaking backward compatibility (forcing a major bump to 2.x.y, which seems silly at this point) or tedious deprecation warnings.

Give me a little time to remind myself how these functions are supposed to work, and I'll get back to you with a solution.  I'll also try to close #29 and #30 while I'm at it.

**Comment by lmaurits** [comment]
Actually this might also be a good place to increase integration with our new Newick package.

**Comment by xrotwang** [comment]
Yes, the formatting of the newick string could be done using `newick.dumps`, in which case the `make_*_structure` functions would have to assemble a `newick.Node` object.

**Comment by xrotwang** [comment]
I ported the sorting behaviour of py2 to py3 via the below key function:

``` python
        def sortkey(i):
            """
            Callable to pass into `sorted` to port sorting behaviour from py2 to py3.

            :param i: Either a string or a list (of lists, ...) of strings.
            :return: Pair (nesting level, first string)
            """
            d = 0
            while isinstance(i, list):
                d -= 1
                i = i[0] if i else ''
            return d, i
```

So we can keep the functionality as is for the moment.

**Comment by lmaurits** [comment]
Okay, great, but even if it now works with Python 3, this function is still in desperate need of a rewrite with heavier commenting!

**Comment by lmaurits** [comment]
Now that tox tests are passing for 2 and 3 for both of us, I'm closing this.  If everybody is good about toxing from now on, hopefully it can stay that way.  Eventually (not urgent) we could probably get some kind of CI happening to make sure we don't break 2+3 compatibility.

**Comment by xrotwang** [comment]
We'd probably have to find a way to mock the BEAST runs, although it seems to be possible to run JAVA on travis-ci.
