### ISSUE TITLE
Calibration specification is too inflexible

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#35]
I realised this while writing a test case for the calibration system.  Currently calibrations can _only_ be specified using Glottolog IDs.  It would be nice if one could just provide a comma-separated list of taxa, e.g.:

[calibrations]
Indo-European = 5000 - 8000
foo, bar, baz = 4800 - 5200

**Comment by xrotwang** [comment]
I can have a crack at that.

**Comment by xrotwang** [comment]
[Comma and spaces in keys](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) seem to be ok, so the syntax you are proposing could work.

**Comment by lmaurits** [comment]
Don't know why this didn't auto-close when I merged the relevant commit.  Closing manually now.
