### ISSUE TITLE
Multiple config files with inheritance

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#45]
Python's ConfigParser (and I presume clldutil's INI which we are using it's place) supports reading multiple config files, with subsequent files able to overwrite the values set by earlier ones.  I've realised it would actually be fantastically powerful if beastling supported this for advanced cases.  One could have a "master.conf" which defines languages, calibrations, models etc. and then say three clock files "strict.conf", "relaxed.conf", "random.conf".  By running:

$ beastling master.conf strict.conf strict.xml
$ beastling master.conf relaxed.conf relaxed.xml
$ beastling master.conf random.conf random.xml

You could get three different versions of the analysis with different clocks.  The advantage is that you can make changes to the languages, calibrations, models etc. in one place instead of three.  Of course you could also fix the clock and have multiple different files for different substitution models, or whatever you want.  You basically get all the power of multiple inheritance in OOP.  I can certainly envision people having standard configuration components that they combine like Mixins.

This could also make our testing setup easier.  Right now we have 33 different config files in tests/configs and 6 in tests/bad_configs/ in order to try various different combinations of settings (and we still don't have full coverage!).  There is a lot of duplication across them and this will only get worse as things progress.  If we could break the different chunks out separately and have the test script assemble different combinations this could cut down our growth rate of config files.

The only sticking point is that the command line syntax proposed above, i.e.:

$ beastling config_1.conf, config_2.conf, ...., config_n.conf, output.xml

does not seem to work smoothly with argparse (if the config file argument was given nargs="+", I believe it would also consume the output file argument).  I'm not sure how best to proceed.  I can see how to hack argparse to make this work, but it would result in the automatically generated usage message being less useful than it is now.

Thoughts?

**Comment by Anaphory** [comment]
With the bonus interpretation of things piping into each other, there would be no problem with making the output file optional (`-o`/`--output`) and printing to `stdout` by default, would there?

**Comment by lmaurits** [comment]
Well, the output file is already optional, and if omitted output goes to <basename>.xml.  I think I would like to keep this behaviour - even enthusiastic plumbers like myself don't _always_ want to write to stdout, and it's no hardship when I do to tack a " -" on the end.  I also don't want to have to force end users to learn about shell redirection just to create a configuration file they can give to BEAST.

**Comment by Anaphory** [comment]
All I meant is: There is hardly any additional hardship writing

```
$ beastling config_1.conf -o output.xml
```

instead of

```
$ beastling config_1.conf output.xml
```

if, on the other hand, that allows you to unambiguously write

```
$ beastling config_1.conf config_2.conf config_3.conf config_4.conf -o output.xml
```

To give the argument more weight, I believe this is the reason why many tools doing a thing like this have the output be the _first_ argument, instead of the _last_. Which I often find confusing, but it prevents this ambiguity, and, even worse, accidentally overwriting your last configuration file because you forgot to specify an output.

**Comment by lmaurits** [comment]
> it prevents this ambiguity, and, even worse, accidentally overwriting your last configuration file because you forgot to specify an output.

BEASTling, of course, will refuse to overwrite an existing file unless you do `--overwrite`. :)

**Comment by lmaurits** [comment]
But, more generally, I now properly understand your proposal.  You mean to change the output from an optional positional argument to an optional non-positional argument.  That might be the best way to achieve this, although it does slightly increase the effort required to print to stdout (`-o -` looks ugly, too!).

**Comment by lmaurits** [comment]
I have implemented this, the usage is:

`$ beastling config_1.conf config_2.conf config_3.conf config_4.conf -o output.xml`

as suggested.  I am a little grumpy about breaking the backward compatibility of the command line interface, but this really seems like the cleanest way to perform this upgrade, which I think is an extremely important one.
