### ISSUE TITLE
Generate reports

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#52]
It would be nice if BEASTling, in addition to the `basename.xml` file containing a BEAST configuration, could optionally generate a human-readable `basename.txt` (or maybe even `basename.pdf` if the user had an optional dependency on some kind of PDF library) report on the analysis.

In particular, the final set of languages in an analysis is often very much implicit - it may be those languages in the intersection of multiple large data files, filtered by Glottolog family (and possibly soon Glottolog macro-area).  The user may not actually know exactly which set of languages they are asking for an analysis of.  A nice, neat summary listing details like the number of languages and the number of Glottolog families they come from, could be handy.

**Comment by xrotwang** [comment]
I think that's a good idea. But I'd rather not go the PDF way. What about markdown, and possibly [geojson](https://help.github.com/articles/mapping-geojson-files-on-github/) - both of which will work very well in a git repository on github.

**Comment by lmaurits** [comment]
Okay, I like that, it will encourage people to store their analyses in Github, which is a good thing.

**Comment by lmaurits** [comment]
This functionality exists now (run BEASTling with `--report`), but I'll be good and not close this until I've documented it.

**Comment by lmaurits** [comment]
Documented and tested.
