### ISSUE TITLE
Read data from stdin, write xml to stdout

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#6]
If beastling would read data from `stdin` and write the BEAST XML to `stdout`, configuration could be shared more elegantly, because no reference to a data file would be needed in the config. This would allow pipelines of the form

``` bash
#!/bin/bash
for macroarea in africa papunesia
do
    csvstack -t Grambank/datasets/$macroarea/*.tsv | beastling grambank.conf > $macroarea.xml
done
```

**Comment by lmaurits** [comment]
This is a great idea, thanks very much!  I will implement it.

**Comment by lmaurits** [comment]
I've taken a first shot at implementing this: to read data from stdin, you can either replace `data = mydata.csv` in the config file's `model` section with `data = stdin`, or you can invoke BEASTling with the `--stdin` option on the command line (which lets you override the filename in an existing config file).  To write the XML to stdout, simply give `-` as a second argument on the commandline (i.e. after the config file).  So, in your example above, the line inside the loop could be:

`csvstack -t Grambank/datasets/$macroarea/*.tsv | beastling grambank.conf - > $macroarea.xml`

if you change grambank.conf to have `data = stdin` or

`csvstack -t Grambank/datasets/$macroarea/*.tsv | beastling --stdin grambank.conf - > $macroarea.xml`

if you leave grambank.conf with a `data` entry pointing at some file.

Note that BEASTling will complain and die if given a config file with a `model` section that does not contain a `data` line, even though this is now potentially a sensible config if stdin is used.  I'll try to remember to make it smarter about this in future.

Please test this thoroughly and feel free to offer any feedback on the details of how it was implemented.

**Comment by Anaphory** [comment]
Note that you can also share configs between different data files by invoking `beastling` from different directories, as observed in #7 (assuming that's working as intended).

**Comment by xrotwang** [comment]
@Anaphory good catch. Sounds a bit [un-pythonic](https://www.python.org/dev/peps/pep-0020/) to me, though:

> Explicit is better than implicit.
