### ISSUE TITLE
XML creation somewhat broken on python 3.4

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#65]
Just came across the following inconsistent behaviour of `ElementTree.tostring` in python 3.4:

```
>>> ET.tostring(ET.Element('a'), encoding='UTF-8')
b'<a />'
```

compared to python 2.7:

```
>>> ET.tostring(ET.Element('a'), encoding='UTF-8')
"<?xml version='1.0' encoding='UTF-8'?>\n<a />"
```

To workaround this issue, we may want to use `ElementTree.ElementTree.write` to serialize `BeastXml` more consistently.

**Comment by lmaurits** [comment]
Looks like you have a fix for this in your fork?  If you submit a PR when you have time I'll accept it and we can close this issue.

**Comment by xrotwang** [comment]
I hope I'll get around to this later in the week.

**Comment by lmaurits** [comment]
Okay, no problem!

**Comment by xrotwang** [comment]
This seems to have been merged into develop already.

**Comment by lmaurits** [comment]
Yep, looks like it.  Closing with thanks.
