### ISSUE TITLE
BEASTling looks for data files relative to pwd, not to config file. Is that intended?

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#7]
When I called `beastling` in a situation where the current working directory was different from the directory the configuration file was located, `beastling` complained about missing the data csv files. They do reside in the same directory as the config, and were specified only by filename (i.e. relative path).

Should `doc/config.rst` explicilty state that the data files are searched relative to `pwd` and not relative to the config file, or should they be relative to the config file no matter what `cwd` is? With the ability to read other values from files, I assume the former, because it permits reusing configuration files.

**Comment by lmaurits** [comment]
Good catch.  I didn't consciously design in behaviour where paths are relative to pwd, I just wrote the simplest thing I could and this is how it turned out.  I'm not sure what I think the best behaviour for this is, I'll have to think about it.

**Comment by Anaphory** [comment]
Just like input from stdin, this can permit reusing/scripting config files. On the other hand, it is confusing at first. So I would suggest some way of writing more generic config files (eg. using a `${…}` notation, or whatever extension to `configparser` already exists), which allows those who need it to use relative-to-pwd paths, and otherwise assume paths are relative to the config file.

**Comment by lmaurits** [comment]
I think I'm going to leave this as is, for now, because the flexibility it affords can be useful, and because if people don't like it there's nothing to stop them including an absolute path in their config file.

**Comment by lmaurits** [comment]
Btw this fact is now documented in docs/config.rst.

**Comment by Anaphory** [comment]
Note: The variable substitution effect I suggested is already in `configparser`, named interpolation: The syntax is `%(variablename)`.
See https://docs.python.org/2/library/configparser.html#configparser-objects for details.
Seeding one variable with the absolute path of the config file would permit specifying machine-independent absolute paths.

**Comment by lmaurits** [comment]
Ah, great!  Thanks for noting that.
