### ISSUE TITLE
Bug: Unresolved reference `model`

### ISSUE THREAD

**Issue by xrotwang** [lmaurits/BEASTling#70]
The symbol `model` in this line https://github.com/lmaurits/BEASTling/blob/a92f72199867fd1869dd694d560d0058c78037ef/beastling/beastxml.py#L77 is not defined.

**Comment by lmaurits** [comment]
I've fixed this, but not pushed yet - there's no test coverage of this line yet, and I wanted to check whether you had an uncommitted test for it (which would explain how you found it) before I wrote my own to push with the fix.

**Comment by xrotwang** [comment]
PyCharm found it. I've only seen the red squiggly underline :)
Am 01.04.2016 21:52 schrieb "Luke Maurits" notifications@github.com:

**Comment by lmaurits** [comment]
Ah, I see! :)  I'll write a test, then.
