### ISSUE TITLE
Languages classed as dialects by Glottolog don't get assigned locations

### ISSUE THREAD

**Issue by lmaurits** [lmaurits/BEASTling#77]
Dialects - which are legitimate choices of language in a dataset for a BEASTling analysis - are not assigned locations in the glottolog-x.y-geo.csv file.  It turns out this causes problems, as the spherical diffusion model does not handle missing data gracefully.  The analysis will run, but any dialects will be assigned a meaningless location, potentially skewing the results.

Is it sensible to have dialects inherit the location of their parent language?  This is an easy fix to code, I just don't know if it is necessarily a safe assumption to make for all of Glottolog.

More generally, does every languoid classed as a "language" have a location, or are some missing?  If there are some languages with no location, we may be forced to drop them from analyses with a geographic component.  Either that or we'll have to edit the spherical diffusion model to handle this situation more gracefully (which _may_ not be too hard).

**Comment by xrotwang** [comment]
Ah, right. Reading just the first line of your comment I thought of the same exact workaround. So yes, I think 
- dialects should inherit the coordinates of the languages, and this should happen in BEASTling,
- not every language in Glottolog does have coordinates.
- It seems to me most transparent to drop languages without location from analyses with geographic component.

We hope to get better data on dialects (including separate coordinates) in the future.

**Comment by lmaurits** [comment]
Okay, great, I will try to make this fix today.  Thanks for the quick response, didn't expect one at 0200!

**Comment by xrotwang** [comment]
I'm in Melbourne :)

**Comment by lmaurits** [comment]
Ach so!  Hope you're enjoying it, I was there about a month ago.  Great city.

**Comment by lmaurits** [comment]
Dialects now inherit their most-recent language-level ancestor's location.  Languages in an analysis with no location data now cause a fatal error, which is of course not a real solution, but it will stop me shooting myself in the foot until I have a chance to write the code to drop them properly.  The logic on whether or not to include a language in an analysis is now getting somewhat complicated and I think I might want to refactor the implementation a bit.

**Comment by lmaurits** [comment]
Languages with no location data are now dropped from analyses with geography, with a notification emitted if `--verbose` is set.
