### ISSUE TITLE
Error when setting language_column with cldf is intransparent

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#83]
I had `language_column = Language_ID` in my beastling configuration file, which I expected to be redundant, but do nothing. However, beastling disagrees:

```
Traceback (most recent call last):
  File "beastling\beastling\cli.py", line 98, in do_generate
    config.process()
  File "beastling\beastling\configuration.py", line 358, in process
    self.instantiate_models()
  File "beastling\beastling\configuration.py", line 581, in instantiate_models
    model = covarion.CovarionModel(config, self)
  File "beastling\beastling\models\covarion.py", line 10, in __init__
    BaseModel.__init__(self, model_config, global_config)
  File "beastling\beastling\models\basemodel.py", line 37, in __init__
    self.build_feature_filter()
  File "beastling\beastling\models\basemodel.py", line 51, in build_feature_filter
    self.features.remove(self.lang_column)
ValueError: list.remove(x): x not in list
```

This should instead either run through, or generate a nice error message along the lines of

> Cannot specify `language_column` for cldf.

**Comment by lmaurits** [comment]
This should be fixed now, and in fact the fix made things overall much simpler and less spread-out, so this was a good bug!  Your redundant specification should run through just fine now, please test when you get a chance.

**Comment by Anaphory** [comment]
Most of this works. If a non-existing language column is specified in the configuration file, but there is a column named `Language_ID` in the CSV, that column is taken and no error is raised.

If both the column specified in the config file and `Language_ID` exist, I get a weird error which is a separate issue.

**Comment by Anaphory** [comment]
For some reason which I must accept full blame because I also can't reproduce it again, it temporarily looked like `language_column` was supported for CLDFs. That is not the case, which is fine, and this is thus closed.
