### ISSUE TITLE
`%l` is not a valid directive for `strftime()`

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#84]
After fixing the errors to my beastling inputs, it still does not run through, but gives me the following traceback.

```
Error encountered while building BeastXML object:
Traceback (most recent call last):
  File "p:\my documents\software\beastling\beastling\cli.py", line 112, in do_generate
    xml = BeastXml(config)
  File "p:\my documents\software\beastling\beastling\beastxml.py", line 32, in __init__
    self.build_xml()
  File "p:\my documents\software\beastling\beastling\beastxml.py", line 45, in build_xml
    self.add_beastling_comment()
  File "p:\my documents\software\beastling\beastling\beastxml.py", line 61, in add_beastling_comment
    comment_lines.append("Generated by BEASTling %s on %s." % (__version__,datetime.datetime.now().strftime("%A, %d %b %Y %l:%M %p")))
ValueError: Invalid format string
```

The directive for a 12h clock is `%I`, not `%l`, which looks very similar in an average sans-serif typeface.

**Comment by lmaurits** [comment]
Okay, this has me really scratching my head.  Reading the documentation, for both Py2 and Py3, you are absolutely right, the hour should be `%I`.  But this bit of code is very old and is very well exercised by the unit tests.  I have been using BEASTling for 3 separate projects for months now and I have never seen this exception.  I have lots of XML files which have correct timestamps in the comment block.

In fact, look at this:

```
148 luke@kuma:~/Development/BEASTling⟫ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.now().strftime("%A, %d %b %Y %l:%M %p")
'Wednesday, 06 Jul 2016 11:41 AM'
>>> 
luke@kuma:~/Development/BEASTling⟫ python2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.now().strftime("%A, %d %b %Y %l:%M %p")
'Wednesday, 06 Jul 2016 11:41 AM
```

I have no idea why my Python installation is accepting this undocumented format directive (and so too is Travis'), and I have no idea why yours is not...

**Comment by lmaurits** [comment]
Ah, okay.  `%l` formats the hour, in 12-hour time, _without_ a leading zero for the first 10 hours of the day.  It is not a part of the C89 standard (which Python's strftime documentation is based on), it is an unofficial extension provided by some implementations of `time.h`.  But support is platform-dependent and possibly locale dependent too.  So replacing it with the standard `%I`, which is guaranteed to work everywhere, and living with the leading zero (which honestly doesn't bother me now, but I guess it must have when I first wrote this) is the correct thing to do.  I will accept your pull request shortly.

**Comment by Anaphory** [comment]
I guess I'm the first Windows user of beastling then. (Stuck with a Windows machine at work for the moment – hopefully not much longer, because for running the beastrun unittests, the downsides of having no decent consistent command line interface really show. On my personal machine at home `%l` works fine, as well)
